source `dirname $0`/util.sh

# It's relatively easy to reproduce a CPUID divergence caused by lack
# of CPU binding.
GLOBAL_OPTIONS="$GLOBAL_OPTIONS_BIND_CPU"

# Ensure that the test records some SCHED interrupt events.
timeslice=100
RECORD_ARGS="-c$timeslice"

# 2^9 iterations is arbitrarily chosen to record and replay < 15s,
# both with and without the syscallbuf, on a fast machine.
record async_signal_syscalls$bitness 9
replay
check 'EXIT-SUCCESS'
