testname=async_signal_syscalls
source util.sh $testname "$@"

# Without the syscallbuf, trying to record the large number of
# syscalls in this test is impractical.
skip_if_no_syscall_buf

record $testname

# Because of issue #184, replay takes longer than practical.  So for
# now we'll skip it and hope other tests exercise the relevant code
# well enough.
#replay
#check 'EXIT-SUCCESS'
echo Test "'$testname'" PASSED
