source `dirname $0`/util.sh

record $TESTNAME &

until grep -q ready record.out; do
  sleep 0
done

pid=$(pidof $TESTNAME-$nonce)
(for i in $(seq 1 1000); do sleep 0; kill -USR1 $pid; done) &
(for i in $(seq 1 1000); do sleep 0; kill -USR2 $pid; done) &
wait %2 || failed "Failed to send all USR1s"
wait %3 || failed "Failed to send all USR2s"
kill -TERM $pid

# Wait for 'record' to actually terminate. Otherwise we might start
# replaying before the trace file has been completely written.
wait %1 || failed "Abnormal record termination"

echo "Replaying ..."
replay
check 'EXIT-SUCCESS'
