testname=deliver_async_signal_during_syscalls
source `dirname $0`/util.sh $testname "$@"

# See async_signal_syscalls.run for an explanation.
skip_if_no_syscall_buf

# SIGUSR1, wait 0.5s
record_async_signal 10 0.5 async_signal_syscalls
# Because of issue #184, replay takes longer than practical.  So for
# now we'll skip it and hope other tests exercise the relevant code
# well enough.
#replay
#check 'EXIT-SUCCESS'
echo Test "'$testname'" PASSED
passed=y
