source `dirname $0`/util.sh deliver_async_signal_during_syscalls "$@"

fails "SIGUSR1 is often delivered while rr processes a time-slice interrupt, and multiple pending signals are NYI"

# See async_signal_syscalls.run for an explanation.
skip_if_no_syscall_buf

# SIGUSR1, wait 0.5s
record_async_signal 10 0.5 async_signal_syscalls
# Because of issue #184, replay takes longer than practical.  So for
# now we'll skip it and hope other tests exercise the relevant code
# well enough.
#replay
#check 'EXIT-SUCCESS'
