source `dirname $0`/util.sh

exe=tcp_sockets$bitness
cp ${OBJDIR}/bin/$exe $exe-$nonce
just_record $exe-$nonce
# The test binary might fail due to IPv6 being unsupported
EXIT_CODE=$?
if [[ `rr dump --socket-addresses latest-trace|grep --count -F 127.0.0.1` != 2 ]]; then
    failed "Wrong number of '127.0.0.1's"
fi
if [[ $EXIT_CODE == 0 ]]; then
  if [[ `rr dump --socket-addresses latest-trace|grep --count -F ::1:` != 2 ]]; then
      failed "Wrong number of '::1:'s"
  fi
fi
