# During this test, try to avoid doing any rr rescheduling. This ensures our
# SIGINT signal will arrive before the "spinning" write syscall has been
# flushed from the syscallbuf. This lets us reliably test that our SIGINT
# handling records and replays such writes correctly.
RECORD_ARGS="-c2000000000"
source `dirname $0`/util.sh term_trace_cpu "$@"

EXE=chew_cpu
SYNC_TOKEN=spinning
WAIT_SECS=1

record $EXE &

echo "Waiting for token '$SYNC_TOKEN' from tracee ..."
until grep -q $SYNC_TOKEN record.out; do
        sleep 0
done

rrpid=$(parent_pid_of $(pidof $EXE-$nonce))

echo "  done.  Delivering SIGINT to $rrpid ..."
kill -INT $rrpid

echo "  done."

# Wait for 'record' to actually terminate. Otherwise we might start
# replaying before the trace file has been completely written, and we might
# fail to see the tracee write EXIT-SUCCESS.
wait

if [[ "record.out" == $(grep -l "EXIT-SUCCESS" record.out) ]]; then
        failed "error during recording: tracer not interrupted in time."
fi

echo "Replaying ..."
replay
check ""
