source `dirname $0`/util.sh term_trace_cpu "$@"

EXE=chew_cpu
SYNC_TOKEN=spinning
WAIT_SECS=1

record $EXE &

until [[ -f record.out ]]; do
    sleep 0.1
done

echo "Waiting for token '$SYNC_TOKEN' from tracee ..."
grep -m1 $SYNC_TOKEN record.out

echo "  done.  Waiting for $WAIT_SECS seconds ..."
sleep $WAIT_SECS

rrpid=$(parent_pid_of $(pidof $EXE-$nonce))

echo "  done.  Delivering SIGINT to $rrpid ..."
kill -INT $rrpid

echo "  done."

if [[ "record.out" == $(grep -l "EXIT-SUCCESS" record.out) ]]; then
   	echo "Test '$TESTNAME' FAILED: error during recording: tracer not interrupted in time."
fi

echo "Replaying ..."
replay
check ""
