TRACE_DIR=trace_0
source `dirname $0`/util.sh trace_version "$@"

function expect_replay_fail {
    replay
    if [[ $(cat replay.err) == "" ]]; then
	echo "Test '$TESTNAME' FAILED: replay should have failed, but it succeeded."
    fi
    echo "  (replay failed as expected)"
}

record simple
if [ ! -f "$TRACE_DIR/version" ]; then
    echo "Test '$TESTNAME' FAILED: version file not found in trace directory."
fi;

echo "Moving version file away ..."
mv "$TRACE_DIR/version" ./version.tmp
expect_replay_fail

echo "Trying to replay with empty version file ..."
echo "" > "$TRACE_DIR/version"
expect_replay_fail

echo "Trying to replay with dummy version number ..."
echo "-42\n" > "$TRACE_DIR/version"
expect_replay_fail

echo "Restoring trace version file ..."
mv ./version.tmp "$TRACE_DIR/version"
replay
check EXIT-SUCCESS
