agents:
  queue: "juliaecosystem"
  sandbox.jl: "true"
  os: "linux"
steps:
  - label: "x86_64"
    key: "x86_64"
    plugins:
      - JuliaCI/julia#v1:
          persist_depot_dirs: packages,artifacts,compiled
          version: '1.6'
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v4.17/rr.x86_64.tar.gz
          rootfs_treehash: "838680473e6ffd8977e1957904d418640e75f69e"
      - JuliaCI/julia#v1:
          persist_depot_dirs: packages,artifacts,compiled
          version: '1.6'
    timeout_in_minutes: 30
    commands: |
      echo "--- Print kernel information"
      uname -a
      echo "--- Print CPU information"
      # These machines have multiple cores. However, it should be sufficient to just print
      # the information for one of the cores. 
      sed -n '1,/^\$/p' /proc/cpuinfo
      echo "--- Generate build environment"
      cmake --version
      rm -rf obj
      mkdir obj
      cd obj
      cmake ..
      echo "--- Build"
      make --output-sync -j8
      echo "--- Test"
      mkdir -p Testing/Temporary
      mv ../.buildkite/CTestCostData.txt Testing/Temporary
      declare -a known_test_failures_array=(
        '^chown$$'
        '^chown-no-syscallbuf$$'
        '^chown-32$$'
        '^chown-32-no-syscallbuf$$'

        '^cwd_inaccessible$$'
        '^cwd_inaccessible-no-syscallbuf$$'
        '^cwd_inaccessible-32$$'
        '^cwd_inaccessible-32-no-syscallbuf$$'

        '^setuid$$'
        '^setuid-no-syscallbuf$$'
        '^setuid-32$$'
        '^setuid-32-no-syscallbuf$$'

        '^sysconf_onln$$'
        '^sysconf_onln-no-syscallbuf$$'
        '^sysconf_onln-32$$'
        '^sysconf_onln-32-no-syscallbuf$$'
      )
      known_test_failures_regex="($$(IFS=\| ; echo "$${known_test_failures_array[*]:?}"))"
      julia ../.buildkite/capture_tmpdir.jl ctest -E "$${known_test_failures_regex:?}" --output-on-failure -j8
