agents:
  queue: "juliaecosystem"
  sandbox.jl: "true"
  os: "linux"
steps:
  - label: "Run-Tests-x86_64"
    key: "Run-Tests-x86_64"
    plugins:
      - JuliaCI/julia#v1:
          persist_depot_dirs: packages,artifacts,compiled
          version: '1.6'
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v4.17/rr.x86_64.tar.gz
          rootfs_treehash: "838680473e6ffd8977e1957904d418640e75f69e"
          verbose: true
          # Mount in the julia installation we used to create the sandbox in the first place
          workspaces:
            - "/cache:/cache"
    timeout_in_minutes: 45
    commands: |
      echo "--- Print kernel information"
      uname -a
      echo "--- Print CPU information"
      # These machines have multiple cores. However, it should be sufficient to just print
      # the information for one of the cores.
      sed -n '1,/^\$/p' /proc/cpuinfo
      echo "--- Generate build environment"
      cmake --version
      rm -rf obj
      mkdir obj
      cd obj
      cmake ..
      echo "--- Build"
      make --output-sync -j$$(nproc)
      echo "--- Test"
      mkdir -p Testing/Temporary
      mv ../.buildkite/CTestCostData.txt Testing/Temporary
      julia ../.buildkite/capture_tmpdir.jl ctest --output-on-failure -j$$(expr $$(nproc) - 2)
